### ISSUE TITLE
Consider smooth scrolling anchors

### ISSUE THREAD

**Issue by xdesro** [jdminnickjr/personal-site#21]
Since the site is a single page layout, it can be beneficial to show users where they navigate to when clicking a link. Lemme know what you think of this effect, which I consider to be a lot less jarring than the instant navigation behavior.

```css
html {
  scroll-behavior: smooth;
}
```
